export const SPECIFICATIONS = {
  MATERIALS: {
    'Metals-Ferrous': [
      'Low Carbon Steel / Mild Steel',
      'Medium Carbon Steel',
      'High Carbon Steel',
      'Tool Steel (D2, A2, O1, S7)',
      'High Speed Steel (HSS)',
      'Stainless Steel 304',
      'Stainless Steel 316',
      'Stainless Steel 17-4 PH',
      'Stainless Steel 303',
      'Cast Iron - Grey',
      'Cast Iron - Ductile',
      'Cast Iron - White',
    ],
    'Metals-Non-Ferrous': [
      'Aluminum 6061-T6',
      'Aluminum 7075-T6',
      'Aluminum 2024-T3',
      'Aluminum 5052-H32',
      'Brass (C360, C260)',
      'Bronze (C932, C954)',
      'Copper (C110, C101)',
      'Titanium Grade 2',
      'Titanium Grade 5 (Ti-6Al-4V)',
      'Magnesium AZ31B',
      'Zinc Alloy (Zamak 3, 5)',
      'Nickel Alloy (Inconel 625, 718)',
      'Monel 400',
    ],
    'Plastics-Thermoplastic': [
      'ABS (Acrylonitrile Butadiene Styrene)',
      'Polycarbonate (PC)',
      'Nylon 6 (PA6)',
      'Nylon 66 (PA66)',
      'Acrylic (PMMA)',
      'Polypropylene (PP)',
      'Polyethylene - HDPE',
      'Polyethylene - LDPE',
      'PVC (Polyvinyl Chloride)',
      'uPVC (Unplasticized PVC)',
      'POM (Delrin/Acetal)',
      'PEEK (Polyether Ether Ketone)',
      'PTFE (Teflon)',
      'Polystyrene (PS)',
      'PET (Polyethylene Terephthalate)',
      'Ultem (PEI)',
    ],
    'Plastics-Thermoset': [
      'Epoxy Resin',
      'Phenolic (Bakelite)',
      'Polyester Resin',
      'Melamine',
      'Polyurethane',
    ],
    Composites: [
      'Carbon Fiber Reinforced Polymer (CFRP)',
      'Glass Fiber Reinforced Polymer (GFRP)',
      'Fiberglass',
      'Kevlar Composite',
    ],
  },
  PROCESS_TYPES: {
    Machined:
      'Part undergoes material removal processes (milling, turning, grinding, drilling)',
    Cast: 'Part is formed by pouring molten material into mold',
    Forged: 'Part is shaped by compressive forces',
    Molded: 'Part is formed in a mold (plastic injection, compression molding)',
    Formed: 'Part is shaped by bending, stamping, or rolling sheet material',
    Additive: 'Part is built layer by layer (3D printing)',
  },
  PROCESSES: [
    'CNC Milling (3-axis)',
    'CNC Milling (4-axis)',
    'CNC Milling (5-axis)',
    'CNC Turning (Lathe)',
    'Swiss Screw Machining',
    'Grinding (Surface)',
    'Grinding (Cylindrical)',
    'Grinding (Centerless)',
    'EDM (Wire)',
    'EDM (Sinker)',
    'Casting (Sand)',
    'Casting (Investment/Lost wax)',
    'Casting (Die casting)',
    'Forging (Hot)',
    'Forging (Cold)',
    'Stamping',
    'Laser Cutting',
    'Waterjet Cutting',
    '3D Printing (Metal)',
    '3D Printing (Plastic)',
    'Injection Molding',
    'Extrusion',
  ],
  MACHINING_OPERATIONS: [
    'Drilling',
    'Reaming',
    'Tapping (through holes)',
    'Tapping (blind holes)',
    'Thread milling',
    'Counterboring',
    'Countersinking',
    'Spotfacing',
  ],
  TOLERANCES: {
    general: [
      'ISO 2768 Fine - \u00b10.05mm to \u00b10.3mm (depending on dimension range)',
      'ISO 2768 Medium - \u00b10.1mm to \u00b10.8mm (depending on dimension range)',
      'ISO 2768 Coarse - \u00b10.2mm to \u00b12mm (depending on dimension range)',
      'ISO 2768 Very Coarse - \u00b10.5mm to \u00b14mm (depending on dimension range)',
    ],
    precision: [
      'IT6 - \u00b10.006mm to \u00b10.019mm (high precision)',
      'IT7 - \u00b10.01mm to \u00b10.03mm (precision)',
      'IT8 - \u00b10.014mm to \u00b10.046mm (normal precision)',
    ],
    gd_and_t: [
      'Flatness',
      'Straightness',
      'Circularity (Roundness)',
      'Cylindricity',
      'Parallelism',
      'Perpendicularity',
      'Angularity',
      'Position',
      'Concentricity',
      'Symmetry',
      'Profile of a Line',
      'Profile of a Surface',
      'Circular Runout',
      'Total Runout',
    ],
    thread: {
      'Metric-ISO': [
        '6H (internal, general purpose)',
        '6g (external, general purpose)',
        '4h6h (close fit)',
        '6e (loose fit)',
      ],
      'Unified-UNC-UNF': [
        '1A/1B (loose fit)',
        '2A/2B (general purpose)',
        '3A/3B (tight, precision)',
      ],
    },
  },
  SURFACE_ROUGHNESS: [
    'N12 (Ra 50) - Very rough - As cast, flame cut',
    'N11 (Ra 25) - Rough - Rough machining',
    'N10 (Ra 12.5) - Coarse - Heavy cuts',
    'N9 (Ra 6.3) - Medium - Standard machining',
    'N8 (Ra 3.2) - Semi-fine - Good machining',
    'N7 (Ra 1.6) - Fine - Precision machining',
    'N6 (Ra 0.8) - Very fine - Fine turning, boring',
    'N5 (Ra 0.4) - Extra fine - Fine grinding',
    'N4 (Ra 0.2) - Super fine - Precision grinding',
    'N3 (Ra 0.1) - Ultra fine - Honing, lapping',
    'N2 (Ra 0.05) - Mirror - Superfinishing',
    'N1 (Ra 0.025) - Super mirror - Lapping, polishing',
  ],
  COATINGS: [
    'Anodizing Type II (Standard)',
    'Anodizing Type III (Hard coat)',
    'Powder Coating',
    'Zinc Plating (Clear)',
    'Zinc Plating (Yellow chromate)',
    'Zinc Plating (Black chromate)',
    'Nickel Plating (Electroless)',
    'Nickel Plating (Electrolytic)',
    'Chrome Plating (Decorative)',
    'Chrome Plating (Hard/Industrial)',
    'Electropolishing',
    'Black Oxide',
    'Phosphate Coating',
    'Cerakote',
    'Teflon Coating',
    'E-coating (Electrocoating)',
    'Powder Coat - Matte',
    'Powder Coat - Gloss',
    'Powder Coat - Textured',
    'Wet Paint - Enamel',
    'Wet Paint - Epoxy',
    'Wet Paint - Polyurethane',
    'Primer Only',
  ],
  SURFACE_TREATMENTS: [
    'Passivation (Citric acid)',
    'Passivation (Nitric acid)',
    'Bead Blasting',
    'Sand Blasting',
    'Tumbling/Vibratory Finishing',
    'Brushing (Satin finish)',
    'Polishing (Mirror finish)',
    'Chemical Etching',
  ],
  HEAT_TREATMENTS: {
    steel: [
      'Annealing',
      'Normalizing',
      'Hardening (Oil quench)',
      'Hardening (Water quench)',
      'Hardening (Air quench)',
      'Tempering',
      'Case Hardening (Carburizing)',
      'Case Hardening (Nitriding)',
      'Case Hardening (Carbonitriding)',
      'Induction Hardening',
      'Flame Hardening',
      'Stress Relieving',
    ],
    aluminum: [
      'Annealing',
      'Solution Heat Treatment',
      'Precipitation Hardening (T4)',
      'Precipitation Hardening (T6)',
      'Natural Aging',
      'Artificial Aging',
    ],
    hardness: {
      Rockwell_C: 'For hardened steels (HRC 20-70)',
      Rockwell_B: 'For softer metals (HRB 0-100)',
      Brinell: 'For general metals (HB 50-750)',
      Vickers: 'For all metals (HV 100-1000)',
    },
  },
  EDGE_BREAK: [
    'Deburr all edges',
    'Break sharp edges C0.2-0.5',
    'Break sharp edges C0.01 max',
    'Break sharp edges C0.015 max',
    'Break sharp edges R0.2-0.5',
    'No deburring required',
    'Tumble deburr',
    'Manual deburr',
    'Brush deburr',
  ],
  SECONDARY_OPERATIONS: {
    assembly: [
      'Press fit',
      'Adhesive bonding',
      'Insert installation (threaded inserts)',
      'Fastener installation',
      'Bushing installation',
      'Final assembly',
    ],
    welding: [
      'TIG Welding',
      'MIG Welding',
      'Spot Welding',
      'Laser Welding',
      'Ultrasonic Welding (plastics)',
      'Heat Staking (plastics)',
    ],
  },
  INSPECTION_METHODS: [
    'CMM (Coordinate Measuring Machine)',
    'Optical comparator',
    'Calipers/Micrometer',
    'Pin gauge',
    'Thread gauge',
    'Surface roughness tester',
    'Hardness tester',
    'First Article Inspection (FAI/AS9102)',
    'Visual Testing (VT)',
    'Ultrasonic Testing (UT)',
    'Radiographic Testing (RT)',
    'Magnetic Particle Testing (MT)',
    'Penetrant Testing (PT/Dye Penetrant)',
    'Eddy Current Testing (ET)',
    'Leak Testing',
    'Thermographic Testing',
  ],
  QUALITY_STANDARDS: [
    'ISO 9001 (General quality)',
    'AS9100 (Aerospace)',
    'ISO 13485 (Medical devices)',
    'IATF 16949 (Automotive)',
    'ISO 14001 (Environmental)',
    'NADCAP (Aerospace special processes)',
  ],
  COMPLIANCE: ['RoHS Compliant', 'REACH Compliant'],
  DOCUMENTATION: [
    'Material Test Certificate (MTC)',
    'Mill Test Report (MTR)',
    'Certificate of Conformance (CoC)',
    'Material Safety Data Sheet (MSDS)',
    'FAI Report (AS9102)',
    'PPAP (Production Part Approval Process)',
    'Material traceability',
    'Heat lot traceability',
  ],
  MARKING_METHODS: [
    'Laser Etching',
    'Laser Engraving',
    'Dot Peen Marking',
    'Stamping',
    'Electrochemical Etching',
    'Ink Printing',
    'Pad Printing',
    'Engraving (mechanical)',
    'No marking required',
  ],
  MARKING_CONTENT: [
    'Part number',
    'Serial number',
    'Date code',
    'Lot/Batch number',
    'Heat number',
    'Manufacturer logo',
    'QR code',
    'Data matrix code',
    'Barcode',
  ],
} as const;
